---
title: "Writing Functions"
output: html_document
date: "2024-11-14"
---


```{r}
library(tidyverse)
library(rvest)
set.seed(1)
```

##My First function 
```{r}
x_vec = rnorm(25, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```


Writing Function for Z scores 
```{r}
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  return(z)
  
}

z_scores(x_vec)
```

Writing what output will retunr if conditions of function not met 
```{r}
z_scores = function(x) {
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  z = mean(x) / sd(x)
  
  return(z)
}
```

##Multiple Outputs 

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

Check that the function works 
```{r}
mean_and_sd(x_vec)
```
##Multiple Inputs 

I'd like to do this with a function 

```{r}
sim_data = tibble(
  x = rnorm(n = 100, mean = 4, sd = 3)
)

sim_data |> 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )

```


```{r}
sim_mean_sd = function(samp_size, mu, sigma) {
  
  sim_data = tibble(
    x = rnorm(samp_size, mean = mu, sd = sigma),
  )
  
  sim_data |> 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
}

sim_mean_sd(100, 6, 3)
```





```{r}

```
